CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    social_id VARCHAR(255) NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NULL,
    name VARCHAR(255) NOT NULL,
    social VARCHAR(255),
    report CHAR,
    image VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);